-- 코드를 입력하세요

SELECT tp.AUTHOR_ID as AUTHOR_ID, a.AUTHOR_NAME as AUTHOR_NAME, tp.CATEGORY as CATEGORY, tp.TOTAL_SALES as TOTAL_SALES
FROM AUTHOR a join
(SELECT b.AUTHOR_ID as AUTHOR_ID, b.CATEGORY as CATEGORY, SUM(s.SALES * b.PRICE) as TOTAL_SALES
from BOOK b join BOOK_SALES s on b.BOOK_ID = s.BOOK_ID
where EXTRACT(YEAR FROM s.SALES_DATE) = 2022 and EXTRACT(MONTH FROM s.SALES_DATE) = 1
group by b.AUTHOR_ID, b.CATEGORY) tp
on tp.AUTHOR_ID = a.AUTHOR_ID
order by a.AUTHOR_ID, CATEGORY desc