-- 코드를 입력하세요
SELECT
p.PRODUCT_CODE as PRODUCT_CODE,
p.PRICE * s.su as SALES
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as su
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) as s JOIN PRODUCT p ON s.PRODUCT_ID = p.PRODUCT_ID
ORDER BY SALES desc, PRODUCT_CODE