-- 코드를 입력하세요
SELECT r2.FOOD_TYPE as FOOD_TYPE, r2.REST_ID as REST_ID, r2.REST_NAME as REST_NAME, ff as FAVORITES
from REST_INFO as r2
join
(SELECT r1.FOOD_TYPE as FOOD_TYPE, MAX(r1.FAVORITES) as ff
from REST_INFO as r1
GROUP BY FOOD_TYPE
) as m on m.FOOD_TYPE = r2.FOOD_TYPE and r2.FAVORITES = m.ff
order by FOOD_TYPE desc
