-- 코드를 입력하세요
SELECT i.ANIMAL_ID as ANIMAL_ID, i.ANIMAL_TYPE as ANIMAL_TYPE, i.NAME  as NAME
FROM ANIMAL_INS as i join ANIMAL_OUTS as j on i.ANIMAL_ID = j.ANIMAL_ID
where i.SEX_UPON_INTAKE != j.SEX_UPON_OUTCOME
order by ANIMAL_ID