-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH , I.GENDER as GENDER ,count(distinct I.user_id) as USERS
FROM USER_INFO as I join ONLINE_SALE as S on S.USER_ID = I.USER_ID
where I.GENDER is not null
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER
order by YEAR, MONTH, GENDER
