SELECT EXTRACT(YEAR FROM s.SALES_DATE) as YEAR, EXTRACT(MONTH FROM s.SALES_DATE) as  MONTH, u.GENDER as GENDER, COUNT(DISTINCT u.USER_ID) as USERS
from USER_INFO u join ONLINE_SALE s on u.USER_ID = s.USER_ID
where u.GENDER is not null
group by EXTRACT(YEAR FROM s.SALES_DATE), EXTRACT(MONTH FROM s.SALES_DATE), u.GENDER
order by YEAR, MONTH, GENDER
