WITH RECURSIVE WR AS (
    SELECT ID , PARENT_ID , 1 AS GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID , A.PARENT_ID , W.GENERATION + 1 FROM ECOLI_DATA A INNER JOIN WR W 
    ON A.PARENT_ID = W.ID
)

SELECT COUNT(*) AS COUNT ,GENERATION
FROM WR WHERE ID NOT IN (SELECT PARENT_ID FROM WR WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION

