-- 코드를 입력하세요
SELECT b.WRITER_ID as USER_ID, u.NICKNAME as NICKNAME, SUM(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD as b join USED_GOODS_USER as u on b.WRITER_ID = u.USER_ID
where b.STATUS = 'DONE'
GROUP BY USER_ID
having SUM(PRICE) >= 700000
order by TOTAL_SALES 
