-- 코드를 입력하세요

WITH MOST as (
    SELECT r1.MEMBER_ID as MEMBER_ID
    FROM REST_REVIEW r1
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM REST_REVIEW r2
        GROUP BY MEMBER_ID    
    )
)


SELECT p.MEMBER_NAME, REVIEW_TEXT, TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
from REST_REVIEW r join MOST m on m.MEMBER_ID = r.MEMBER_ID
join MEMBER_PROFILE p on p.MEMBER_ID = r.MEMBER_ID
order by REVIEW_DATE, REVIEW_TEXT
