SELECT KID.ID AS ID, KID.GENOTYPE AS GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS KID
JOIN ECOLI_DATA AS PARENT
ON PARENT.ID = KID.PARENT_ID
WHERE KID.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY ID