-- 코드를 작성해주세요
SELECT MAX_YEAR.YEAR as YEAR,
MAX_YEAR.m - e.SIZE_OF_COLONY as YEAR_DEV,
e.ID as ID
FROM (SELECT MAX(SIZE_OF_COLONY) as m,
      YEAR(DIFFERENTIATION_DATE) as YEAR
     FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)
     ) as MAX_YEAR
JOIN ECOLI_DATA as e on MAX_YEAR.YEAR = YEAR(e.DIFFERENTIATION_DATE)
order by YEAR, YEAR_DEV