-- 코드를 입력하세요
SELECT 
CONCAT('/home/grep/src/', file.BOARD_ID,  '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE file JOIN USED_GOODS_BOARD board ON board.BOARD_ID = file.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC

# SELECT *
# FROM USED_GOODS_FILE

# SELECT *
# FROM USED_GOODS_BOARD
# ORDER BY VIEWS DESC